version: '3'
services:
  hip:
    build: .
    ports:
      - "9052:80"
    environment: 
      - HEALTH_CHECK_DURATION=5000
    depends_on:
      - db
      - rabbitmq
      - otp
    restart: unless-stopped
  otp:
    image: "ganesan92/otp-service"
    depends_on:
      - db
  gateway:
    build: gatewayStubConfigurations/.
    ports:
      - "2525:2525"
      - "8000:8000"
  oidc-server-mock:
    image: soluto/oidc-server-mock
    ports:
      - "8080:80"
    environment:
      API_SCOPES_INLINE: |
        [
          "some-app-scope-1"
        ]
      CLIENTS_CONFIGURATION_PATH: /gatewayStubConfigurations/oicdConfigs/clients-config.json
    volumes:
      - ./gatewayStubConfigurations/oicdConfigs/clients-config.json:/gatewayStubConfigurations/oicdConfigs/clients-config.json
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  rabbitmq:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
  filebeat:
    container_name: filebeat
    build:
      context: .
      dockerfile: filebeat.Dockerfile
    volumes:
      - ./logs:/var/log
    networks:
      - elk
  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

volumes:
  postgresql:
  postgresql_data:
    
networks:
  elk:
    external: true